Med 8 add up down scroll
spavelo/medias pull request #5
Opened 2021-12-21 20:16 UTC by spavelo

2021-12-21 20:48 UTC, SVladikO commented on src/App.js
> +import {Wrapper, Content, A} from "./App.styles";
A?

2021-12-21 20:53 UTC, SVladikO requested changes

2021-12-21 20:53 UTC, SVladikO commented on src/App.js
> +                <A href={'#down'}><BsFillCaretDownFill className={'goToDown'}/></A>
Please use size attribute

2021-12-21 20:53 UTC, SVladikO commented on src/App.js
> +                <A href={"#top"}><BsFillCaretUpFill className='goToTop'/></A>
The same

2021-12-21 20:53 UTC, SVladikO commented on src/index.css
> +.goToDown, .goToTop {
Use this styles for as parent>*

2021-12-21 20:55 UTC, spavelo commented on src/App.js
> +import {Wrapper, Content, A} from "./App.styles";
A is a styled-component element

2021-12-22 11:42 UTC, spavelo commented on src/App.js
> +                <A href={'#down'}><BsFillCaretDownFill className={'goToDown'}/></A>
fixed

2021-12-22 11:43 UTC, spavelo commented on src/App.js
> +                <A href={"#top"}><BsFillCaretUpFill className='goToTop'/></A>
fixed

2021-12-22 11:43 UTC, spavelo commented on src/index.css
> +.goToDown, .goToTop {
fixed

2021-12-22 19:00 UTC, SVladikO approved these changes
Good job

2021-12-22 19:00 UTC, SVladikO commented on src/App.styles.js
> +    flex-direction: row;
is it default value ?

2021-12-22 19:00 UTC, SVladikO commented on src/common/QuickScrolls/QuickScrolls.component.js
> +            <a name={'down'}></a>
separate this row with SGoTop

2021-12-22 19:00 UTC, SVladikO commented on src/common/QuickScrolls/QuickScrolls.component.js
> +            <SGoTop href={"#top"}><BsFillCaretUpFill style={iconStyle}/></SGoTop>
SGoTop bad name

2021-12-22 19:02 UTC, merged